using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using FluentAssertions;

namespace FinBeat.TaskManagement.UnitTests.Architecture;

/// <summary>
/// Keeps AI-assistant attribution out of the source tree.
/// </summary>
/// <remarks>
/// Tooling markers — assistant names, vendor names, session links, "generated by" trailers — are an
/// artefact of how a file was produced, not of what it does. They date the code, leak internal
/// workflow into a deliverable, and carry no information a reader can act on. Authorship belongs in
/// version control, which already records it.
/// </remarks>
public sealed partial class AuthorshipConventionTests
{
    /// <summary>
    /// File extensions worth scanning: everything a human reads as part of the source.
    /// </summary>
    private static readonly string[] ScannedExtensions = [".cs", ".csproj", ".props", ".targets", ".json", ".md", ".yml", ".yaml"];

    /// <summary>Shared build files that sit beside the solution rather than inside a project.</summary>
    private static readonly string[] RootBuildFiles =
    [
        "Directory.Build.props",
        "Directory.Packages.props",
        ".editorconfig",
        "global.json",
        "README.md",
    ];

    [Fact]
    public void Source_files_carry_no_ai_assistant_attribution()
    {
        var offenders = ScannableFiles()
            .SelectMany(FindMarkers)
            .OrderBy(offender => offender, StringComparer.Ordinal)
            .ToArray();

        offenders.Should().BeEmpty(
            "assistant and vendor attribution is an artefact of how a file was produced, not part of "
            + "the deliverable - version control already records authorship");
    }

    private static IEnumerable<string> FindMarkers(FileInfo file)
    {
        var lineNumber = 0;

        foreach (var line in File.ReadLines(file.FullName))
        {
            lineNumber++;

            if (AttributionMarker().IsMatch(line))
            {
                yield return $"{file.Name}:{lineNumber}: {line.Trim()}";
            }
        }
    }

    /// <summary>
    /// Every scannable file belonging to a project the solution actually contains.
    /// </summary>
    /// <remarks>
    /// Driven off the solution's project list rather than a directory walk, so agent scratch space
    /// and nested checkouts under the repository root are out of scope by construction — the same
    /// reason <see cref="SolutionLayout"/> reads the solution file instead of globbing.
    /// </remarks>
    private static IEnumerable<FileInfo> ScannableFiles()
    {
        // This rule declares the very strings it forbids, so it would always flag itself.
        var ownFileName = Path.GetFileName(OwnSourcePath());

        var options = new EnumerationOptions
        {
            RecurseSubdirectories = true,
            IgnoreInaccessible = true,
        };

        // Repository-root build files, named explicitly rather than by walking the root: a recursive
        // walk would descend into nested checkouts and agent scratch directories, which is the same
        // trap SolutionLayout avoids by reading the solution file.
        foreach (var rootFile in RootBuildFiles)
        {
            var file = new FileInfo(Path.Combine(SolutionLayout.RepositoryRoot.FullName, rootFile));

            if (file.Exists)
            {
                yield return file;
            }
        }

        foreach (var layer in ArchitectureModel.AllLayers.Append(ThisTestProject))
        {
            var projectFile = SolutionLayout.ProjectFile(layer);

            yield return projectFile;

            foreach (var file in projectFile.Directory!.EnumerateFiles("*", options))
            {
                var isBuildOutput = Path
                    .GetRelativePath(projectFile.DirectoryName!, file.DirectoryName!)
                    .Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                    .Any(segment => segment is "bin" or "obj");

                if (isBuildOutput
                    || string.Equals(file.Name, ownFileName, StringComparison.Ordinal)
                    || !ScannedExtensions.Contains(file.Extension, StringComparer.OrdinalIgnoreCase))
                {
                    continue;
                }

                yield return file;
            }
        }
    }

    private const string ThisTestProject = "FinBeat.TaskManagement.UnitTests";

    private static string OwnSourcePath([CallerFilePath] string path = "") => path;

    // Matches the assistant and vendor names plus the trailers that carry them, so a renamed
    // trailer ("Generated with ...", a session permalink) is caught even without the name.
    [GeneratedRegex(
        @"claude|anthropic|co-authored-by:\s*(claude|.*\bai\b)|generated\s+with\s+\[?claude|claude\.ai",
        RegexOptions.IgnoreCase)]
    private static partial Regex AttributionMarker();
}
