namespace FinBeat.TaskManagement.Listener;

/// <summary>
/// Sample background service generated by the project template. Out of scope for this task and
/// will be replaced by the message listener implementation in a later phase.
/// </summary>
public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="Worker"/> class.
    /// </summary>
    /// <param name="logger">Logger used to report worker activity.</param>
    public Worker(ILogger<Worker> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Runs the background service loop until cancellation is requested.
    /// </summary>
    /// <param name="stoppingToken">Token used to signal cancellation of the service.</param>
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            if (_logger.IsEnabled(LogLevel.Information))
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
            }

            await Task.Delay(1000, stoppingToken);
        }
    }
}