namespace FinBeat.TaskManagement.Application;

/// <summary>
/// Placeholder type generated by the project template. The Application layer is out of scope for
/// this task and will be replaced in a later phase.
/// </summary>
public class Class1
{
}