<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\FinBeat.TaskManagement.Domain\FinBeat.TaskManagement.Domain.csproj" />
        <ProjectReference Include="..\FinBeat.TaskManagement.Contracts\FinBeat.TaskManagement.Contracts.csproj" />
    </ItemGroup>

</Project>
