using System.Security.Cryptography;

namespace FinBeat.TaskManagement.Domain.Tasks;

/// <summary>
/// Strongly-typed identifier for a <c>TaskItem</c>, wrapping a UUID version 7 (RFC 9562)
/// <see cref="Guid"/>.
/// </summary>
/// <param name="Value">The underlying identifier value.</param>
/// <remarks>
/// <para>
/// <b>Why the id is generated by the client, not the database.</b> A task has an identity from the
/// instant it is constructed, not from the instant it is saved. <c>Entity&lt;TId&gt;</c> compares
/// entities by their id, so if ids were assigned by a database sequence, every unsaved task would
/// carry <see cref="Guid.Empty"/> until it was persisted — two <em>different</em> freshly created
/// tasks would compare equal in the meantime, and inserting both into a <see cref="HashSet{T}"/>
/// would silently keep only one. Assigning the id in <see cref="New"/>, before the aggregate is ever
/// handed to a repository, removes that whole failure mode.
/// </para>
/// <para>
/// <b>Why version 7 specifically.</b> A random UUID (version 4) would satisfy uniqueness equally
/// well, but a version 7 id embeds a millisecond timestamp in its high-order bytes, so ids minted
/// close together in time sort close together in value. PostgreSQL's <c>uuid</c> column type
/// compares byte-wise, most significant byte first, so a version 7 primary key clusters newly
/// inserted rows together in the index instead of scattering them randomly across it — the same
/// benefit an auto-incrementing key gives, without giving up client-side generation. This is a
/// PostgreSQL-specific payoff: SQL Server's <c>uniqueidentifier</c> collation reorders bytes before
/// comparing (the last six bytes sort ahead of the rest), which defeats a big-endian, time-ordered
/// layout, so the same scheme would not cluster inserts there.
/// </para>
/// </remarks>
public readonly record struct TaskItemId(Guid Value)
{
    /// <summary>Generates a new id from the current time, laid out as a UUID version 7 (RFC 9562).</summary>
    /// <param name="clock">Supplies the timestamp embedded in the id. The domain never reads the ambient clock directly.</param>
    /// <returns>A new, unique <see cref="TaskItemId"/>.</returns>
    public static TaskItemId New(TimeProvider clock)
    {
        ArgumentNullException.ThrowIfNull(clock);

        Span<byte> bytes = stackalloc byte[16];

        // Bytes 0-5: 48-bit Unix timestamp in milliseconds, big-endian.
        var unixMilliseconds = clock.GetUtcNow().ToUnixTimeMilliseconds();
        bytes[0] = (byte)(unixMilliseconds >> 40);
        bytes[1] = (byte)(unixMilliseconds >> 32);
        bytes[2] = (byte)(unixMilliseconds >> 24);
        bytes[3] = (byte)(unixMilliseconds >> 16);
        bytes[4] = (byte)(unixMilliseconds >> 8);
        bytes[5] = (byte)unixMilliseconds;

        // Bytes 6-15: filled with random data, then the version and variant bits are stamped
        // over the top so the random fill never has to know about the UUIDv7 layout.
        RandomNumberGenerator.Fill(bytes[6..]);
        bytes[6] = (byte)((bytes[6] & 0x0F) | 0x70); // high nibble = version 0111 (7)
        bytes[8] = (byte)((bytes[8] & 0x3F) | 0x80); // high 2 bits = variant 10

        return new TaskItemId(new Guid(bytes, bigEndian: true));
    }

    /// <summary>Wraps an existing <see cref="Guid"/> value as a <see cref="TaskItemId"/>, for example when rehydrating an id from storage.</summary>
    /// <param name="value">The underlying value. Must not be <see cref="Guid.Empty"/>.</param>
    /// <returns>A <see cref="TaskItemId"/> wrapping <paramref name="value"/>.</returns>
    /// <exception cref="ArgumentException"><paramref name="value"/> is <see cref="Guid.Empty"/>.</exception>
    public static TaskItemId From(Guid value)
    {
        if (value == Guid.Empty)
        {
            throw new ArgumentException("A task id cannot be an empty guid.", nameof(value));
        }

        return new TaskItemId(value);
    }

    /// <inheritdoc />
    public override string ToString() => Value.ToString();
}
