namespace FinBeat.TaskManagement.Infrastructure;

/// <summary>
/// Placeholder type generated by the project template. The Infrastructure layer is out of scope
/// for this task and will be replaced in a later phase.
/// </summary>
public class Class1
{
}